# Generated by Django 2.2.5 on 2020-05-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('tipo_cosecha', models.CharField(choices=[('frutas', 'Fruta'), ('Vegetales', 'Vegetales')], max_length=50)),
                ('id_cosecha', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cosecha', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('vitamina', models.CharField(max_length=100)),
                ('temperatura', models.CharField(max_length=100)),
                ('tiempo_de_riego', models.CharField(max_length=150)),
                ('humedad_de_tierra', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': ('Cosecha',),
                'verbose_name_plural': ('Cosechas',),
                'db_table': 'Cosecha',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=20)),
                ('planta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50, verbose_name='ingrese la region')),
                ('temperatura', models.CharField(max_length=20)),
                ('plantas', models.CharField(max_length=20)),
                ('id_provinvia', models.ManyToManyField(to='eat_for_thought.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50, verbose_name='Nombre de pais')),
                ('id_region', models.ManyToManyField(related_name='region_pais', to='eat_for_thought.Region')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCosecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curacion_Cosecha', models.CharField(max_length=150)),
                ('casos_de_cosecha', models.TextField()),
                ('foto', models.ImageField(upload_to='imagenes_cosecha/')),
                ('vide_instuctivo', models.URLField()),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cosechas', to='eat_for_thought.Cosecha')),
            ],
            options={
                'verbose_name': ('DetalleCosecha',),
                'verbose_name_plural': ('DetalleCosechas',),
                'db_table': 'DetalleCosecha',
            },
        ),
    ]
